### ISSUE TITLE
Want moving_mnist code

### ISSUE THREAD

**Issue by toddwyl** [JessieYuW/CrevNet-Traffic4cast#1]
```
from data.moving_mnist import MovingMNIST
from data.bair import RobotPush
from data.kth128 import KTH
```
I read the code `data_utils.py` which have these files, and can you offer me the moving_mnist.py and kth128.py code ?

**Comment by gnosisyuw** [comment]
You can find the moving_mnist.py in the following link.
https://drive.google.com/file/d/1koVpH2RhkOl4_Xm_q8Iy1FuX3zQxC9gd/view?usp=sharing
